<?xml version='1.0' encoding='utf-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.selenium</groupId>
        <artifactId>cucumber-projects</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>parabank-cucumber-tests</artifactId>
    <properties>
        <cucumber.filter.tags>not @disabled</cucumber.filter.tags>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.selenium</groupId>
            <artifactId>common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-testng</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <cucumber.filter.tags>${cucumber.filter.tags}</cucumber.filter.tags>
                    </systemPropertyVariables>
                    <includes combine.self="override">
                        <include>**/TestRunnerAll.java</include>
                    </includes>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>Smoke</id>
            <properties>
                <cucumber.filter.tags>@smoke</cucumber.filter.tags>
            </properties>
        </profile>
        <profile>
            <id>Regression</id>
            <properties>
                <cucumber.filter.tags>not @disabled</cucumber.filter.tags>
            </properties>
        </profile>
    </profiles>
</project>
